# agent.py — AI Research Assistant Agent

from dotenv import load_dotenv
import os
import datetime
load_dotenv()

from tavily import TavilyClient
from langchain_groq import ChatGroq
from langchain.agents import create_react_agent, AgentExecutor
from langchain.tools import Tool
from langchain_core.prompts import PromptTemplate


# ── Web Search ────────────────────────────────────────────────────────────
def search_web(query, max_results=3):
    client = TavilyClient(api_key=os.getenv("TAVILY_API_KEY"))
    results = client.search(
        query=query,
        search_depth="advanced",
        max_results=max_results,
        include_answer=True,
    )
    return results


def format_search_results(results):
    output = []
    if results.get("answer"):
        output.append(f"Quick Summary: {results['answer']}")
        output.append("")
    for i, result in enumerate(results["results"], 1):
        output.append(f"[Source {i}]")
        output.append(f"Title: {result['title']}")
        output.append(f"URL: {result['url']}")
        output.append(f"Content: {result['content'][:150]}")
        output.append("-" * 40)
    return "\n".join(output)


# ── Tool ──────────────────────────────────────────────────────────────────
def tavily_search_tool(query: str) -> str:
    results = search_web(query, max_results=2)
    return format_search_results(results)


tools = [
    Tool(
        name="WebSearch",
        func=tavily_search_tool,
        description=(
            "Search the web for current and accurate information. "
            "Use this tool when you need up-to-date facts, recent "
            "developments, statistics, expert opinions, or any "
            "information that requires current knowledge. "
            "Input should be a specific and focused search query. "
            "Use different queries each time to gather diverse information."
        )
    )
]


# ── ReAct Prompt ──────────────────────────────────────────────────────────
REACT_PROMPT_TEMPLATE = """You are an expert research assistant with access to web search.
Your job is to research any topic thoroughly and produce a comprehensive report.

You have access to these tools:
{tools}

Tool names: {tool_names}

To complete a research task, use this EXACT format every time:

Thought: [think about what aspect to research first]
Action: WebSearch
Action Input: [your specific search query]
Observation: [search results will appear here automatically]
Thought: [analyse results and decide what else to search]
Action: WebSearch
Action Input: [different search query to cover another angle]
Observation: [search results]
Thought: [continue until you have enough for a full report]
Thought: I now have comprehensive information to write the research report.
Final Answer: [your complete structured research report]

IMPORTANT RULES:
1. Always search at least 3 times with DIFFERENT queries
2. Each query should explore a DIFFERENT aspect of the topic
3. Never repeat the same search query twice
4. Cite source URLs in your final answer
5. Structure your Final Answer with EXACTLY these sections:

## RESEARCH REPORT: [Topic Title]

### Executive Summary
[2-3 sentence overview of the key findings]

### Key Findings
[5-7 bullet points of the most important facts]

### Detailed Analysis
[3-4 paragraphs of in-depth analysis]

### Current Trends (2025-2026)
[What is happening right now in this area]

### Sources
[List all URLs you found information from, one per line]

---
Report generated by AI Research Assistant Agent

Once you write the Final Answer, do not write anything else.

Question: {input}
{agent_scratchpad}"""

prompt = PromptTemplate(
    template=REACT_PROMPT_TEMPLATE,
    input_variables=["tools", "tool_names", "input", "agent_scratchpad"]
)


# ── Build Agent ───────────────────────────────────────────────────────────
def build_agent():
    llm = ChatGroq(
        model_name="llama-3.1-8b-instant",
        temperature=0.1,
        max_tokens=4096,
        api_key=os.getenv("GROQ_API_KEY")
    )

    agent = create_react_agent(
        llm=llm,
        tools=tools,
        prompt=prompt
    )

    executor = AgentExecutor(
        agent=agent,
        tools=tools,
        verbose=True,
        max_iterations=10,
        handle_parsing_errors=True,
        return_intermediate_steps=True
    )

    return executor


# ── Extract Report ────────────────────────────────────────────────────────
def extract_report(result: dict) -> str:
    output = result.get("output", "")

    if "RESEARCH REPORT" in output:
        return output

    steps = result.get("intermediate_steps", [])
    best_report = ""

    for step in steps:
        if isinstance(step, tuple):
            for part in step:
                part_str = str(part)
                if "RESEARCH REPORT" in part_str:
                    start = part_str.find("## RESEARCH REPORT")
                    candidate = part_str[start:]
                    candidate = candidate.replace('\\n', '\n')
                    if len(candidate) > len(best_report):
                        best_report = candidate

    if best_report:
        return best_report

    return output if output else "Research could not be completed. Please try again."


# ── Research Function ─────────────────────────────────────────────────────
def research_topic(topic: str, retry: bool = False) -> str:
    """
    Main function — takes a research topic and returns a structured report.
    Automatically retries with smaller content if token limit is hit.
    """
    print(f"\nStarting research on: {topic}")
    print("=" * 60)

    try:
        executor = build_agent()
        result = executor.invoke({"input": topic})
        report = extract_report(result)
        return report

    except Exception as e:
        error_str = str(e)

        # Handle token limit error — retry with smaller content
        if "413" in error_str or "rate_limit" in error_str.lower():
            if not retry:
                print("Token limit hit — retrying with smaller content...")
                # Temporarily reduce content size globally
                import agent as self_module
                original = self_module.format_search_results

                def smaller_format(results):
                    output = []
                    if results.get("answer"):
                        output.append(f"Summary: {results['answer'][:150]}")
                    for i, r in enumerate(results["results"][:2], 1):
                        output.append(f"[{i}] {r['title']}")
                        output.append(f"URL: {r['url']}")
                        output.append(f"{r['content'][:100]}")
                        output.append("---")
                    return "\n".join(output)

                self_module.format_search_results = smaller_format
                try:
                    result = research_topic(topic, retry=True)
                finally:
                    self_module.format_search_results = original
                return result

        raise e

# ── PDF Helper ────────────────────────────────────────────────────────────
def _safe(text: str, max_len: int = 110) -> str:
    """Convert text to latin-1 safe string for PDF generation."""
    if len(text) > max_len:
        text = text[:max_len] + "..."
    return text.encode("latin-1", "replace").decode("latin-1")


# ── PDF Export ────────────────────────────────────────────────────────────
def save_report_as_pdf(topic: str, report: str) -> str:
    from fpdf import FPDF

    pdf = FPDF()
    pdf.add_page()
    W = 180

    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(13, 43, 94)
    pdf.set_xy(15, 15)
    pdf.cell(W, 12, "AI Research Report", ln=True, align="C")

    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(80, 80, 80)
    topic_display = topic[:70] + "..." if len(topic) > 70 else topic
    pdf.set_x(15)
    pdf.cell(W, 8, f"Topic: {topic_display}", ln=True, align="C")
    pdf.set_x(15)
    pdf.cell(W, 7,
        f"Generated: {datetime.datetime.now().strftime('%B %d, %Y at %H:%M')}",
        ln=True, align="C")
    pdf.ln(6)

    pdf.set_draw_color(26, 86, 168)
    pdf.line(15, pdf.get_y(), 195, pdf.get_y())
    pdf.ln(6)

    pdf.set_text_color(44, 44, 44)

    for line in report.split("\n"):
        line = line.strip()
        if not line:
            pdf.ln(3)
            continue

        pdf.set_x(15)

        if line.startswith("## "):
            pdf.set_font("Helvetica", "B", 14)
            pdf.set_text_color(13, 43, 94)
            pdf.multi_cell(W, 9, _safe(line.replace("## ", ""), 100))
            pdf.set_text_color(44, 44, 44)
            pdf.ln(2)

        elif line.startswith("### "):
            pdf.set_font("Helvetica", "B", 11)
            pdf.set_text_color(26, 86, 168)
            pdf.multi_cell(W, 8, _safe(line.replace("### ", ""), 100))
            pdf.set_text_color(44, 44, 44)
            pdf.ln(1)

        elif line.startswith("* ") or line.startswith("- "):
            pdf.set_font("Helvetica", "", 9.5)
            pdf.multi_cell(W, 6, _safe("  -  " + line[2:], 110))

        elif line.startswith("---"):
            pdf.set_draw_color(200, 200, 200)
            pdf.line(15, pdf.get_y(), 195, pdf.get_y())
            pdf.ln(4)

        elif line.startswith("http"):
            pdf.set_font("Helvetica", "", 8)
            pdf.set_text_color(26, 86, 168)
            pdf.multi_cell(W, 5, _safe(line, 100))
            pdf.set_text_color(44, 44, 44)

        else:
            pdf.set_font("Helvetica", "", 9.5)
            pdf.multi_cell(W, 6, _safe(line, 110))

    pdf.ln(8)
    pdf.set_x(15)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(W, 6,
        "Generated by AI Research Assistant Agent · LangChain · Tavily · Groq Llama-3.1",
        align="C")

    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"research_{timestamp}.pdf"
    pdf.output(filename)
    print(f"PDF saved: {filename}")
    return filename


# ── Test Block ────────────────────────────────────────────────────────────
if __name__ == "__main__":

    print("=" * 60)
    print("AGENT + PDF EXPORT TEST")
    print("=" * 60)

    topic = "What is prompt engineering and what are the best techniques in 2026?"

    report = research_topic(topic)

    print("\n" + "=" * 60)
    print("FINAL REPORT:")
    print("=" * 60)
    print(report[:500])
    print("...")

    print("\n" + "=" * 60)
    print("SAVING AS PDF:")
    print("=" * 60)
    pdf_file = save_report_as_pdf(topic, report)
    print(f"PDF created: {pdf_file}")
    print("Open it in your file explorer to verify formatting.")
